### ISSUE TITLE
Command /jffs/lagdrop_ps4.sh permission denied

### ISSUE THREAD

**Issue by d4nc3r69** [42Kmi/LagDrop#2]
Hi,

I get the error message permission denied when try to run the command.

In addition to that, I created the 42Kmi folder by my own put the options_ps4.txt in and changed the IP.

For a test run, I put my PC IP in and wanted to execute it via putty.

Can you please tell me how I can execute runlagdrop.sh via putty?

sorry, for my stupid questions.

thanks

**Comment by 42Kmi** [comment]
Those aren't stupid questions. What router do you have? What firmware and
version?

1. Make sure you've chmod the all the LagDrop script to 755.

2. Execute runlagdrop.sh as "/jffs/runlagdrop.sh ps4"

Substitute for the actual directory where you placed the LagDrop scripts. I
recommend adding it to cronjobs. The instructions are in the readme

Thanks for checking out LagDrop

On Jun 29, 2017 4:11 PM, "d4nc3r69" <notifications@github.com> wrote:

Hi,

I get the error message permission denied when try to run the command.

In addition to that, I created the 42Kmi folder by my own put the
options_ps4.txt in and changed the IP.

For a test run, I put my PC IP in and wanted to execute it via putty.

Can you please tell me how I can execute runlagdrop.sh via putty?

sorry, for my stupid questions.

thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/42Kmi/LagDrop/issues/2>, or mute the thread

**Comment by d4nc3r69** [comment]
[router_stuff.pdf](https://github.com/42Kmi/LagDrop/files/1113801/router_stuff.pdf)

I have a Netgear R7000.

In Screenshot No. 1 you can see DD-WRT Details (Firmware etc..) and the error message when I try top the script.

Screenshot No. 2: Chmod is 755 (but if I tick set group owner....; click ok and go again in this window, everytime it's unticked, is this normal?

Screenshot No. 3: location of the lagdrop files

Thank you for your help.

**Comment by 42Kmi** [comment]
Tick the "set group, owner, and permissions recursively" box

In the "Administration" tab of DD-wrt web interface, enable Cron and add
the following without quotes as an additional cron job:
    "*/1 * * * * root /bin/sh /jffs/runlagdrop.sh ps4"

This will execute runlagdrop.sh every minute to ensure it's running. But
don't worry. LagDrop will only run if your console is on and will prevent
parallel execution of itself.

**Comment by 42Kmi** [comment]
also, try just running lagdrop_ps4.sh. See if it goes through

**Comment by d4nc3r69** [comment]
I enabled already cron and put the command in. I played already on ps4 two games. How I know if it works? 
I ticked as well set group, but then in dd-wrt undet commands I cannot execute (error permission denied) 
The question is, stays the tick in winscp for set group owner or not, because as already mentioned, everytime if I'm checking the folder then set group is unticked?)

**Comment by 42Kmi** [comment]
chmod to 777 then.
You can check if it's running buy running lagdropcount.sh

**Comment by d4nc3r69** [comment]
I will try it when I at home. Thanks

can I run lagdropcount.sh via dd-wrt Command or how can I do it?

this the location of the file:
/jffs/lagdropcound.sh

**Comment by 42Kmi** [comment]
You can run it in command

**Comment by d4nc3r69** [comment]
I still have this issue. I changed the chmod via WinSCP but still not work.
Do you have any other ideas?
[2.pdf](https://github.com/42Kmi/LagDrop/files/1116021/2.pdf)

**Comment by d4nc3r69** [comment]
In the attachment you can find my routersettings as well:
Administration and Services
[3.pdf](https://github.com/42Kmi/LagDrop/files/1116056/3.pdf)

**Comment by 42Kmi** [comment]
Another option would be to downgrade. I've heard before that there had been
issues with LagDrop on recent builds of DD-WRT. Maybe install a build from
mid 2016.

I haven't been able to work on LagDrop since I've been busy with med school.

On Jun 30, 2017 1:33 PM, "d4nc3r69" <notifications@github.com> wrote:

In the attachment you can find my routersettings as well:
Administration and Services
3.pdf <https://github.com/42Kmi/LagDrop/files/1116056/3.pdf>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/42Kmi/LagDrop/issues/2#issuecomment-312327990>, or mute
the thread

**Comment by 42Kmi** [comment]
I originally wrote LagDrop on a router running DD-WRT v24-sp2 (20/04/15)
std. It's been reported that LagDrop hasn't been running on
31570M/31575M/31780M. So try downgrading a version a few before 31573M.
Hope this helps.

**Comment by d4nc3r69** [comment]
I tried it now in putty and now I get this error. It looks like, that the script is not running for my router?
[4.pdf](https://github.com/42Kmi/LagDrop/files/1116781/4.pdf)

**Comment by 42Kmi** [comment]
That's actually a peculiar find. I'll have to look into that. Thanks

**Comment by 42Kmi** [comment]
Try editing using the lagdrop_wiiu.sh script and see what happens. Open it,
find CONSOLENAME=, change the identifier from wiiu to ps4. Save, and rename
it to lagdrop_ps4.sh

**Comment by d4nc3r69** [comment]
I tried it as well with the wiiu.sh file but it's the same.
But I found this out, how should I download the .sh files. Because in this 2 different ways I get different error messages (see attached).
[5.pdf](https://github.com/42Kmi/LagDrop/files/1117001/5.pdf)

**Comment by 42Kmi** [comment]
download Notepad++

Sorry, it feels like I'm making you do more work than you should

**Comment by d4nc3r69** [comment]
I downloaded notepad++ and atom. 
Then I clicked on your files, copied the data out and paste it in the new file. Name is the same like you did. But if run it in putty, then I get everytime an error. syntax, special lines etc.

I need this script because I want to play FUT Champions and want to check the connections.
I don't know what I can do, that lagdrop works corretly.

**Comment by d4nc3r69** [comment]
Can it be, that your scripts when you uploaded here on this page are now wrongly scripted?
Because when I check lagdrop_ps4.sh then I get this error message in the script:

https://www.shellcheck.net/

I checked with this site.

I will try to clean it and see if it works.
Or what do you think?

**Comment by 42Kmi** [comment]
Here's something I did not catch before:

Open lagdrop_ps4.sh, go to line 49

Change -f to -d. Save.

See if that fixes anything.

**Comment by d4nc3r69** [comment]
Is also not working. I think it doesn't work with this router :( I don't know. It looks like that I have to buy the overpriced Netduma R1.
![grafik](https://user-images.githubusercontent.com/29784552/27765815-d74d3434-5ebc-11e7-976b-ed1d5da7128c.png)

**Comment by d4nc3r69** [comment]
But thank you for your help and support.

**Comment by 42Kmi** [comment]
Thank you, because I was able to find a previously overlooked mistake.

I don't think your router is the problem. It may be the DD-WRT version it's
running. Maybe downgrading to an earlier version will help.

**Comment by d4nc3r69** [comment]
I used Dec 2014, March 2015and this here // Firmware: DD-WRT v24-sp2 (07/01/15).
Everytime the same error's with the script.

**Comment by 42Kmi** [comment]
Could you share the contents of your options.txt file?

**Comment by d4nc3r69** [comment]
Every .sh script which I try to run via Putty or DD-WRT I get an error.
