### ISSUE TITLE
SSBU peer detection not working on OpenWRT-18.06

### ISSUE THREAD

**Issue by Driphter** [42Kmi/LagDrop#5]
I'm not having any luck getting the script to work. Half the time I run it, I get disconnected from my SSH/SCP sessions. The other half the time when the status screen show up, it never detects any peers when I play people online.

Is there any sort of debug/error log file or mode that I can use to help diagnose the problem? It's hard to figure out what's going on when the source is obfuscated.

**Comment by 42Kmi** [comment]
Hello,

First and foremost, thank you for showing interest in using LagDrop. I've
been working on this for so long and it's nice to see people curious about
it. From my testing on OpenWRT and DD-WRT, I've seen that it does work. I
know the instructions included are brief, but I am working on making a more
detailed document.
Could you share some detail about your set up?
-Did you set your Switch to a Static IP? If using a wired connection, use
should use the Ethernet adapter's IP and MAC address when setting the
Static IP.

-Did you check the 42Kmi directory for your options.txt file? You can add
your console's [Ethernet adapter] IP address there manually. It autofills
if there is already a Static IP set.

-When running, if you have set your static IP, for example, if you named
your Switch "Driphter_Switch" and run "./lagdrop.sh switch" LagDrop will
find the first instance of Switch among the names in the Static IP list and
grab that IP as the one to use when initiating the
options_Driphter_Switch.txt file.

After reading your message I push an updated LagDrop and included a
non-obfuscated lagdrop.sh to the repository. Hope that helps.

Also, could you link me to any screenshots of your terminal as you run
lagdrop?

Again, thanks for checking out LagDrop.

**Comment by 42Kmi** [comment]
I found those bugs and corrected them. Hopefully it should run without
closing your terminal. Please update and check

**Comment by Driphter** [comment]
I'm already using a static IP, but I'll test out the update and report back, thanks!

**Comment by Driphter** [comment]
The disconnection is definitely gone, but it's still not picking up peers. The only thing it's doing differently is detecting `192.xx.xx.1` which I assume is my gateway of `192.168.1.1`.

![Screenshot](https://user-images.githubusercontent.com/196429/57561185-4c8aec80-7358-11e9-91cd-8daaf6259c7e.PNG)

**Comment by 42Kmi** [comment]
So I JUST pushed another update to the repository. It corrects one of the
bugs you encountered (initially meant to prevent multiple instances of
lagdrop.sh from running, fixed so it won't terminate the terminal), then I
fixed some more I encountered. Also, make sure you have openssl-util
installed for OpenWRT. I hardreset my OpenWRT router to run through the
LagDrop setup again. Not having openssl-util installed will cause LagDrop
to misbehave (no reading peers). Make a huge difference.

**Comment by Driphter** [comment]
Yep, `openssl-util` is installed. I tried updating the script again, but I'm still only seeing `192.xx.xx.1` like in the screenshot above.

**Comment by 42Kmi** [comment]
Could you share a pic of your options.txt, the static IP assigned to your
Switch on the router's web interface, and the Switch's IP address on the
Internet setting page on the Switch?

Is there a 42Kmi/cache folder with files in it? Do you see the
filterignore, pingmem and geomem files?

**Comment by 42Kmi** [comment]
Make sure you have curl installed. If that doesn't solve it, try installing
libcurl.

**Comment by Driphter** [comment]
No luck after installing `curl`.

![options txt](https://user-images.githubusercontent.com/196429/57573713-24ec6080-73fa-11e9-9783-6c7c8c1a54aa.png)

![dhcp-lease](https://user-images.githubusercontent.com/196429/57573773-7812e300-73fb-11e9-870b-b31a04e95098.PNG)

![dhcp-static](https://user-images.githubusercontent.com/196429/57573774-7a753d00-73fb-11e9-9b6a-713d764e4f3a.PNG)

![switch-settings](https://user-images.githubusercontent.com/196429/57573791-b8726100-73fb-11e9-833f-c83bf3bddd3b.jpg)

![switch-status](https://user-images.githubusercontent.com/196429/57573792-bc9e7e80-73fb-11e9-96a8-e6f8b46ce93e.jpg)

![root-42kmi](https://user-images.githubusercontent.com/196429/57573828-7eee2580-73fc-11e9-9256-f458715bcb96.PNG)

![root-42kmi-cache](https://user-images.githubusercontent.com/196429/57573829-81e91600-73fc-11e9-8f64-6b07ecbc26aa.PNG)

![cahe-files](https://user-images.githubusercontent.com/196429/57573830-86adca00-73fc-11e9-9a50-ec22a5e09235.PNG)

**Comment by 42Kmi** [comment]
Go get the latest lagdrop update. Delete the cache folder. Install curl and
libcurl. Then try again. I also added a stay awake for OpenWRT, which
basically pings and curls example.com every 5 seconds.

After installing curl and libcurl on my OpenWRT router I stopped seeing the
Taipei results for all IPs. Maybe that had to do with curl not being on the
system, so it just defaulted to Taipei? Weird.

Walk me through what you have set up.
What kind of router?
Is lagdrop.sh installed on the router?
Is the Switch directly connected to the same router?

Another option to try is to make a "debug" options.txt. Run "lagdrop.sh
debug -s -l" It's just like running lagdrop the same as any other time, but
the will load the non-filter that's used for PC, etc, which doesn't omit
console-specific servers from being tested against LagDrop. Go to the
options_debug.txt and add your Switch's IP address. Hopefully you'll see
something.

You can also do the debug thing with your phone or PC or whatever. Browser
the internet a bit. Hopefully you will see the montior populate.

Also, could you send a pic of all available commands in your terminal?
Press tab twice.

As far as I can tell, I'm not seeing anything on my end, but if I can
compare your available commands against my own I may be able to see what
may be missing.

In the meantime, you can try running without location. That may still work,
but it will remove the location-enabled features.

Thanks again. I hope to get this working for you because it's really
impressive when it works.

**Comment by 42Kmi** [comment]
You can try flushing your iptables with "iptables -F"

**Comment by Driphter** [comment]
I have a Linksys WRT1900AC v1 with a fresh install of OpenWRT 18.06. I've updated all of the packages. `lagdrop.sh` is installed in `/root/`. My Switch is connected directly to the router via an Ethernet adapter.

I just tried setting it up with the "debug" options and didn't have any luck. Every now and then a random IP will show up, but nothing that was unique per game. Tried it with my computer's IP and my phone's IP and nothing came up. Maybe the IP filter is too strict? No luck removing the `-l` flag.

Here's the commands we're working with:
![commands](https://user-images.githubusercontent.com/196429/57575775-2e3bf400-741f-11e9-96c7-40d0901b632a.PNG)

Thanks for the help, I really appreciate it!

**Comment by 42Kmi** [comment]
Please check the /proc/net/ directory. Do you see nf_conntrack or
ip_conntrack?

**Comment by 42Kmi** [comment]
I pushed another update. Hopefully it fixes LagDrop for you. If that
doesn't work, do you want to try it on DD-WRT? I'm running OpenWrt 18.06.2
r7676-cddd7b4c77 on a NETGEAR R6100 and am not having any issues. IP's are
logging and disappearing on my OpenWRT. Some stay for a bit then disappear,
which is normal since LagDrop does clear IPs that are no longer connected
to the router. I have my OpenWRT LagDrop listening to the router.

**Comment by 42Kmi** [comment]
It may be fixed now. Please check.

**Comment by Driphter** [comment]
I just played against a few people on the latest update and no peer showed up. :( Maybe it's a location thing? I'm in MI, USA if that helps. I might try DD-WRT at some point, it's just a matter of finding a good day to do it, since I'm going to have to kick everyone and everything off of the internet to do it lol.

**Comment by 42Kmi** [comment]
I don't have anything specifically blocking Michigan. That would be weird
if I did. If you updated within about 1 hour of when I wrote this reply, I
did push another update.

**Comment by 42Kmi** [comment]
Hold off on installing DD-WRT. I might be onto something now. I think I
finally solved. Thanks for bearing with me. I'll let you know when to
update again.

**Comment by 42Kmi** [comment]
Could you run this in your terminal and send a screenshot of the result?

tail +1 "/proc/net/nf_conntrack"|grep -Ev "^192.168.1.13"|grep -Eo
"(([0-9]{1,3}\.?){3})\.([0-9]{1,3})"|sort -u|grep -Ev "^192.168.1.1"|grep
-Ev "^192.168"

**Comment by Driphter** [comment]
To answer an earlier question, I have `nf_conntrack`, but no `ip_conntrack`.

Here's the result of that command:
![image](https://user-images.githubusercontent.com/196429/57588016-f5ae2000-74db-11e9-9f2a-45f2d41b86bd.png)

I didn't have the Switch on when I did it though. Did you mean for me to do it while in a game with a peer?
